/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  GetBusinessProfileIDResponse,
  getBusinessProfileIDResponseSchema,
} from '../models/getBusinessProfileIDResponse';
import {
  SuccessResponse,
  successResponseSchema,
} from '../models/successResponse';
import {
  UpdateBusinessProfileRequest,
  updateBusinessProfileRequestSchema,
} from '../models/updateBusinessProfileRequest';
import { optional, string } from '../schema';
import { BaseController } from './baseController';

export class BusinessProfilesController extends BaseController {
  /**
   * Use this endpoint to retrieve your business’ profile. This business profile is visible to consumers
   * in the chat thread next to the profile photo. The profile information will contain a business
   * profile ID which you can use to make API calls.
   *
   * @param phoneNumberID
   * @param fields          Here you can specify what you want to know from your business as a comma
   *                                  separated list of fields. Available fields include: id, about, messaging_product,
   *                                  address, description, vertical, email, websites, profile_picture_url
   * @return Response from the API call
   */
  async getBusinessProfileID(
    phoneNumberID: string,
    fields?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetBusinessProfileIDResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      phoneNumberID: [phoneNumberID, string()],
      fields: [fields, optional(string())],
    });
    req.query('fields', mapped.fields);
    req.appendTemplatePath`/${mapped.phoneNumberID}/whatsapp_business_profile`;
    return req.callAsJson(getBusinessProfileIDResponseSchema, requestOptions);
  }

  /**
   * Use this endpoint to update your business’ profile information such as the business description,
   * email or address.
   *
   * @param phoneNumberID
   * @param body
   * @return Response from the API call
   */
  async updateBusinessProfile(
    phoneNumberID: string,
    body: UpdateBusinessProfileRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      phoneNumberID: [phoneNumberID, string()],
      body: [body, updateBusinessProfileRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/${mapped.phoneNumberID}/whatsapp_business_profile`;
    return req.callAsJson(successResponseSchema, requestOptions);
  }
}
