/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  SetTwoStepVerificationCodeRequest,
  setTwoStepVerificationCodeRequestSchema,
} from '../models/setTwoStepVerificationCodeRequest';
import {
  SuccessResponse,
  successResponseSchema,
} from '../models/successResponse';
import { string } from '../schema';
import { BaseController } from './baseController';

export class TwoStepVerificationController extends BaseController {
  /**
   * You are required to set up two-step verification for your phone number, as this provides an extra
   * layer of security to the business accounts. You can use this endpoint to change two-step
   * verification code associated with your account.
   * After you change the verification code, future requests like changing the name, must use the new
   * code.
   *
   * You set up two-factor verification and register a phone number in the same API call.
   *
   * @param phoneNumberID
   * @param body
   * @return Response from the API call
   */
  async setTwoStepVerificationCode(
    phoneNumberID: string,
    body: SetTwoStepVerificationCodeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      phoneNumberID: [phoneNumberID, string()],
      body: [body, setTwoStepVerificationCodeRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/${mapped.phoneNumberID}`;
    return req.callAsJson(successResponseSchema, requestOptions);
  }
}
