/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { BusinessProfile, businessProfileSchema } from './businessProfile';

export interface GetBusinessProfileIDResponse {
  data: BusinessProfile[];
}

export const getBusinessProfileIDResponseSchema: Schema<GetBusinessProfileIDResponse> = object(
  { data: ['data', array(lazy(() => businessProfileSchema))] }
);
