/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { QualityRatingEnum, qualityRatingEnumSchema } from './qualityRatingEnum';

export interface GetPhoneNumberByIDResponse {
  /** The verified name associated with the phone number. */
  verifiedName: string;
  /** The string representation of the phone number. */
  displayPhoneNumber: string;
  /** The ID associated with the phone number. */
  id: string;
  /** The quality rating of the phone number based on how messages have been received by recipients in recent days. */
  qualityRating: QualityRatingEnum;
}

export const getPhoneNumberByIDResponseSchema: Schema<GetPhoneNumberByIDResponse> = object(
  {
    verifiedName: ['verified_name', string()],
    displayPhoneNumber: ['display_phone_number', string()],
    id: ['id', string()],
    qualityRating: ['quality_rating', qualityRatingEnumSchema],
  }
);
