/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Document, documentSchema } from './document';
import { HeaderTypeEnum, headerTypeEnumSchema } from './headerTypeEnum';
import { Image, imageSchema } from './image';
import { Video, videoSchema } from './video';

export interface Header {
  /** The header type you would like to use. */
  type: HeaderTypeEnum;
  /** Required if type is set to text. Text for the header. Formatting allows emojis, but not markdown. */
  text?: string;
  /** Required if type is set to video. Contains the media object for this video. */
  video?: Video;
  /** Required if type is set to image. Contains the media object for this image. */
  image?: Image;
  /** Required if type is set to document. Contains the media object for this document. */
  document?: Document;
}

export const headerSchema: Schema<Header> = object({
  type: ['type', headerTypeEnumSchema],
  text: ['text', optional(string())],
  video: ['video', optional(lazy(() => videoSchema))],
  image: ['image', optional(lazy(() => imageSchema))],
  document: ['document', optional(lazy(() => documentSchema))],
});
