/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Currency, currencySchema } from './currency';
import { DateTimeObject, dateTimeObjectSchema } from './dateTimeObject';
import { Document, documentSchema } from './document';
import { Image, imageSchema } from './image';
import { ParameterTypeEnum, parameterTypeEnumSchema } from './parameterTypeEnum';
import { Video, videoSchema } from './video';

export interface Parameter {
  /** Describes the parameter type. For text-based templates, the only supported parameter types are text, currency, date_time. */
  type: ParameterTypeEnum;
  /** Required when type=text. The message’s text. For the header component, the character limit is 60 characters. For the body component, the character limit is 1024 characters. */
  text?: string;
  /** Required when type=currency. */
  currency?: Currency;
  /** Required when type=date_time. */
  dateTime?: DateTimeObject;
  /** Required when type=image. */
  image?: Image;
  /** Required when type=document. Only PDF documents are supported for media-based message templates. */
  document?: Document;
  /** Required when type=video. */
  video?: Video;
}

export const parameterSchema: Schema<Parameter> = object({
  type: ['type', parameterTypeEnumSchema],
  text: ['text', optional(string())],
  currency: ['currency', optional(lazy(() => currencySchema))],
  dateTime: ['date_time', optional(lazy(() => dateTimeObjectSchema))],
  image: ['image', optional(lazy(() => imageSchema))],
  document: ['document', optional(lazy(() => documentSchema))],
  video: ['video', optional(lazy(() => videoSchema))],
});
