/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RegisterPhoneRequest {
  /** Messaging service used. In this case, use "whatsapp". */
  messagingProduct: string;
  /** A 6-digit pin you have previously set up - See Set Two-Step Verification. */
  pin: string;
}

export const registerPhoneRequestSchema: Schema<RegisterPhoneRequest> = object({
  messagingProduct: ['messaging_product', string()],
  pin: ['pin', string()],
});
