/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import {
  RequestVerificationCodeMethodEnum,
  requestVerificationCodeMethodEnumSchema,
} from './requestVerificationCodeMethodEnum';

export interface RequestVerificationCodeRequest {
  /** Chosen method for verification. */
  codeMethod: RequestVerificationCodeMethodEnum;
  /** Your locale. For example: "en_US". */
  locale: string;
}

export const requestVerificationCodeRequestSchema: Schema<RequestVerificationCodeRequest> = object(
  {
    codeMethod: ['code_method', requestVerificationCodeMethodEnumSchema],
    locale: ['locale', string()],
  }
);
