/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** A 6-digit pin you wish to use for two-step authentication. */
export interface SetTwoStepVerificationCodeRequest {
  pin: string;
}

export const setTwoStepVerificationCodeRequestSchema: Schema<SetTwoStepVerificationCodeRequest> = object(
  { pin: ['pin', string()] }
);
