/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Component, componentSchema } from './component';
import { Language, languageSchema } from './language';

export interface Template {
  /** Name of the template. */
  name: string;
  /** Specifies the language the template may be rendered in. Only the deterministic language policy works with media template messages. */
  language: Language;
  /** Array of components objects containing the parameters of the message. */
  components?: Component[];
}

export const templateSchema: Schema<Template> = object({
  name: ['name', string()],
  language: ['language', lazy(() => languageSchema)],
  components: ['components', optional(array(lazy(() => componentSchema)))],
});
