/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UploadMediaRequest {
  /** Messaging service used for the request. In this case, use whatsapp. */
  messagingProduct: string;
  /** Path to the file stored in your local directory. For example: "@/local/path/file.jpg". */
  file: string;
  /**
   * Type of media file being uploaded. See Supported Media Types for more information.
   *  Supported options for images are: `image/jpeg`, `image/png`
   *  Supported options for documents are: `text/plain`, `application/pdf`, `application/vnd.ms-powerpoint`, `application/msword`, `application/vnd.ms-excel`, `application/vnd.openxmlformats-officedocument.wordprocessingml.document`, `application/vnd.openxmlformats-officedocument.presentationml.presentation`, `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
   * Supported options for audio are: `audio/aac`, `audio/mp4`, `audio/mpeg`, `audio/amr`, `audio/ogg`, `audio/opus`
   * Supported options for video are: `video/mp4`, `video/3gp`
   * Supported options for stickers are: `image/webp`
   */
  type: string;
}

export const uploadMediaRequestSchema: Schema<UploadMediaRequest> = object({
  messagingProduct: ['messaging_product', string()],
  file: ['file', string()],
  type: ['type', string()],
});
