/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface VerifyCodeRequest {
  /** The code you received after calling FROM_PHONE_NUMBER_ID/request_code. */
  code: string;
}

export const verifyCodeRequestSchema: Schema<VerifyCodeRequest> = object({
  code: ['code', string()],
});
