/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VerticalEnum
 */
export enum VerticalEnum {
  UNDEFINED = 'UNDEFINED',
  OTHER = 'OTHER',
  AUTO = 'AUTO',
  BEAUTY = 'BEAUTY',
  APPAREL = 'APPAREL',
  EDU = 'EDU',
  ENTERTAIN = 'ENTERTAIN',
  EVENTPLAN = 'EVENT_PLAN',
  FINANCE = 'FINANCE',
  GROCERY = 'GROCERY',
  GOVT = 'GOVT',
  HOTEL = 'HOTEL',
  HEALTH = 'HEALTH',
  NONPROFIT = 'NONPROFIT',
  PROFSERVICES = 'PROF_SERVICES',
  RETAIL = 'RETAIL',
  TRAVEL = 'TRAVEL',
  RESTAURANT = 'RESTAURANT',
  NOTABIZ = 'NOT_A_BIZ',
}

/**
 * Schema for VerticalEnum
 */
export const verticalEnumSchema: Schema<VerticalEnum> = stringEnum(VerticalEnum);
